import type { EmailMessage } from '../types'

/**
 * The employee-invitation email.
 *
 * Pure: takes data, returns strings, touches nothing. That is what makes it
 * unit-testable without a transport, a database, or a network — and it is why
 * templates live here rather than inline in lib/employees/mutations.ts.
 *
 * Deliberately hand-written HTML with inline styles and a table-free layout.
 * Email clients are not browsers: no external stylesheet loads, Outlook
 * ignores most of what does load, and Tailwind's classes mean nothing here.
 * A React email renderer would be a dependency and a build step for one
 * message; a second one arrives in Milestone 12, at which point this file is
 * the pattern to copy, not the thing to replace.
 */

export interface EmployeeInvitationEmailInput {
  inviteUrl: string
  organizationName: string
  roleName: string
  inviterName: string
  expiresAt: Date
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function formatExpiry(expiresAt: Date): string {
  return expiresAt.toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

export function renderEmployeeInvitationEmail(
  input: EmployeeInvitationEmailInput,
): Pick<EmailMessage, 'subject' | 'html' | 'text'> {
  const { inviteUrl, organizationName, roleName, inviterName, expiresAt } = input
  const expiry = formatExpiry(expiresAt)

  // Every value that reaches the HTML is organization-supplied free text
  // (an org name, a custom role name, a person's full name), so all of it is
  // escaped. The URL is generated by lib/employees/invitations.ts from
  // NEXT_PUBLIC_APP_URL plus a base64url token — no user input in it — but it
  // is escaped too rather than relying on that staying true.
  const html = `<!doctype html>
<html lang="en">
  <body style="margin:0;padding:24px;background:#f5f5f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#0a0a0a;">
    <div style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:12px;padding:32px;">
      <h1 style="margin:0 0 16px;font-size:20px;font-weight:600;">
        You have been invited to ${escapeHtml(organizationName)}
      </h1>
      <p style="margin:0 0 16px;font-size:15px;line-height:1.6;">
        ${escapeHtml(inviterName)} has invited you to join
        <strong>${escapeHtml(organizationName)}</strong> as
        <strong>${escapeHtml(roleName)}</strong>.
      </p>
      <p style="margin:0 0 24px;font-size:15px;line-height:1.6;">
        Set up your account to accept this invitation.
      </p>
      <a href="${escapeHtml(inviteUrl)}"
         style="display:inline-block;padding:12px 20px;background:#059669;color:#ffffff;text-decoration:none;border-radius:8px;font-size:15px;font-weight:600;">
        Accept invitation
      </a>
      <p style="margin:24px 0 0;font-size:13px;line-height:1.6;color:#525252;">
        This invitation expires on ${escapeHtml(expiry)} and can only be used once.
        If the button does not work, paste this link into your browser:
        <br />
        <span style="word-break:break-all;">${escapeHtml(inviteUrl)}</span>
      </p>
      <p style="margin:16px 0 0;font-size:13px;line-height:1.6;color:#525252;">
        If you were not expecting this invitation, you can ignore this email.
      </p>
    </div>
  </body>
</html>`

  // The URL must appear here too: this is what the log transport prints, what
  // a plain-text client shows, and what a screen reader reads.
  const text = [
    `${inviterName} has invited you to join ${organizationName} as ${roleName}.`,
    '',
    'Set up your account to accept this invitation:',
    inviteUrl,
    '',
    `This invitation expires on ${expiry} and can only be used once.`,
    'If you were not expecting this invitation, you can ignore this email.',
  ].join('\n')

  return {
    subject: `You have been invited to join ${organizationName}`,
    html,
    text,
  }
}
