-- Milestone 09's root table (docs/milestones/09-customer-store-credit-and-
-- layaway.md Database Changes). Deliberately `organization_id`-scoped and
-- NOT branch-scoped: this milestone's Scope is explicit that a customer
-- record is "business-wide (not branch-scoped) — a customer record is shared
-- across the organization's branches, per docs/Business_Structure_Branche.md
-- §24.42's 'business-wide customers'". Its RLS policy therefore uses
-- public.user_has_org_access() (20260822093300_create_authorization_
-- functions.sql), not user_has_branch_access() the way every M07/M08 table
-- does — the one place in the transactional schema where that difference is
-- intentional rather than an oversight.
--
-- No loyalty/tier/customer-group/preferences columns, per this milestone's
-- Implementation Notes ("Resist adding customer loyalty/tiering fields 'just
-- in case' — explicitly out of scope per docs/PRD.md §24"). A future loyalty
-- feature extends this table additively without disturbing the ledgers.
--
-- `customer_code` is the human-facing identifier (docs/Customer Management_
-- Store_Credit_and_Layaway.md §46) — unique per organization, generated by
-- lib/customers/mutations.ts, not a database sequence, so it can carry an
-- org-readable prefix later without a type migration.
--
-- `archived_at` (not `status`/`is_active`), per docs/architecture/database-
-- conventions.md — customers are tenant/operational data whose history must
-- survive archival because sales/ledger rows reference them.
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,

  customer_code text not null,
  name text not null,
  phone text,
  email text,
  address text,
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users(id) on delete set null,
  archived_at timestamptz
);

create index customers_organization_id_idx on public.customers (organization_id);

-- Partial-unique on the archived_at convention (same shape as
-- products_business_unit_sku_key): an archived customer's code/phone/email
-- can be reused. phone/email are nullable, and a NULL never conflicts with
-- another NULL in a unique index, so unidentified walk-in-style records are
-- unaffected.
create unique index customers_organization_code_key
  on public.customers (organization_id, customer_code) where archived_at is null;
create unique index customers_organization_phone_key
  on public.customers (organization_id, phone) where archived_at is null and phone is not null;
create unique index customers_organization_email_key
  on public.customers (organization_id, lower(email)) where archived_at is null and email is not null;

-- Name search reuses the pg_trgm extension already enabled by
-- 20260823100600_create_product_search_indexes.sql — this milestone's
-- customer identification ("phone/email/name") needs the same fast
-- `ILIKE '%term%'` path products already use, and no new search service
-- (docs/TAS.md §36).
create index customers_name_trgm_idx on public.customers using gin (name gin_trgm_ops);

create trigger trg_customers_updated_at
  before update on public.customers
  for each row execute function public.set_updated_at();

alter table public.customers enable row level security;
