-- Payment records for subscription renewals
-- (docs/milestones/13-subscription-billing-and-platform-admin.md Database
-- Changes: "subscription_payments (payment records, Paystack reference,
-- verification status)").
--
-- THE PENDING ROW IS WRITTEN AT CHECKOUT INITIATION, before the browser ever
-- reaches Paystack. This is the load-bearing design decision in the whole
-- payment layer, for two reasons:
--
--   1. `paystack_reference` is OUR OWN generated value (lib/paystack/
--      reference.ts), not one Paystack hands back — so the webhook/callback
--      settlement path (apply_subscription_payment, 20260825100600) resolves
--      organization_id / subscription_id / billing_period / expected
--      amount_minor from THIS row, never from the Paystack payload. Paystack
--      contributes only "did this succeed, and for how much" — exactly the
--      Technical Requirement's "never activated based solely on the
--      frontend's Paystack response".
--
--   2. Idempotent settlement is a conditional UPDATE, not a second lookup
--      table: `update ... set status = 'SUCCESS' ... where paystack_reference
--      = $1 and status = 'PENDING' returning *`. A replayed webhook or a
--      duplicate browser callback finds zero rows and extends nothing — the
--      same on-conflict-do-nothing shape Milestone 08's create_sale() uses
--      for its idempotency_key, applied as a state-transition guard instead
--      of an insert conflict, which additionally gives atomic single-winner
--      semantics if the webhook and the browser callback race each other.
create table public.subscription_payments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  subscription_id uuid not null references public.subscriptions(id) on delete cascade,

  paystack_reference text not null unique,
  paystack_transaction_id bigint,

  billing_period text not null
    check (billing_period in ('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL')),
  amount_minor bigint not null check (amount_minor > 0),
  currency text not null default 'NGN' check (currency ~ '^[A-Z]{3}$'),

  status text not null default 'PENDING'
    check (status in ('PENDING', 'SUCCESS', 'FAILED', 'ABANDONED')),

  authorization_url text,
  initiated_by uuid references public.users(id) on delete set null,

  verified_at timestamptz,
  verification_response jsonb,
  failure_reason text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.subscription_payments.paystack_reference is
  'Generated by this application (lib/paystack/reference.ts) at checkout '
  'initiation, never by Paystack. The identity the webhook and the browser '
  'callback both settle against — see the table comment.';

comment on column public.subscription_payments.verification_response is
  'Paystack''s verify-transaction response body, stored for the '
  'Observability requirement. Paystack returns only a masked card '
  'last4/bin, never a full PAN, so this is safe to persist as-is.';

create trigger subscription_payments_set_updated_at
  before update on public.subscription_payments
  for each row execute function public.set_updated_at();

create index subscription_payments_org_created_idx
  on public.subscription_payments (organization_id, created_at desc);

-- Supports a bounded scan for stuck checkouts (abandoned-payment cleanup /
-- support diagnostics) without a sequential scan of the whole table.
create index subscription_payments_pending_idx
  on public.subscription_payments (created_at)
  where status = 'PENDING';

alter table public.subscription_payments enable row level security;
